# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59ad915c628aa3027bf3be54641e0eb95e570baa7ebed1973f54b4fb74c226e1af5958107b93a72a3f525c2b1628480f5b624cb089b9820f8cbcd34d1e4fa2a7

test:
  secret_key_base: ee10753527fac74473f71be8ee33981e8a211de5249d1447bc61ab45769ab3d88db3da47465ce467254ee8a042922763dd95b508b3bb70319fa97ad71bb9472a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
